# CI de Nìvel 01 - Disparo manual a partir de 1 clique
name: 'Execução Manual'

on:
  workflow_dispatch:

jobs:

  e2e-tests:

    runs-on: ['ubuntu-latest']

    steps:
      - uses: actions/checkout@v4

      - name: Instalando Yarn
        run: npm install -g yarn

      - name: Instalando dependências
        run: yarn

      - name: Instalando Playwright
        run: yarn global add typescript

      - name: Levantar o servidor em background
        working-directory: ./crud_clientes_node-main/backend
         run: node app.js start &

      - name: Testes E2E (end-to-end)
        working-directory: trabalho-entregue
        run: yarn run e2e
        env:
          URL: 'http://localhost:3000'

      # passed, failed, cancelled
      - uses: actions/upload-artifact@v4
        if: ${{ !cancelled() }}
        with:
          name: relatorio-de-testes
          path: ./typescript-report
