# CI de Nível 01 - Disparo Manual a partir de 1 clique

# noome que aparece nas opções da pipe

name: "Execução Manual"

# regras de disparo da excucao (triggers)

on:
  workflow_dispatch:

jobs:

  # descricao do job
  e2e-tests:

    # maquina que o job vai executar
    runs-on: ['ubuntu-latest'] 

    # passo a passo das acoes do job
    steps: 

    - uses: actions/checkout@v4

    - name: Instalando Yarn
      run: cd trabalho-entregue npm install -g yarn

    - name: Instalando dependências
      run: cd trabalho-entregue yarn  

    - name: Instalando Playwright
      run: cd trabalho-entregue yarn playwright install

    - name: Levantar o servidor
      run: cd crud_clientes_node-main/backend node app.js

    - name: Testes E2E (end-to-end)  
      run: cd trabalho-entregue yarn run e2e


