# CI de Nível 01 - Disparo Manual a partir de 1 clique

# noome que aparece nas opções da pipe

name: "Execução Manual"

# regras de disparo da excucao (triggers)

on:
  workflow_dispatch:

jobs:

  # descricao do job
  e2e-tests:

    # maquina que o job vai executar
    runs-on: ['ubuntu-latest'] 

    # passo a passo das acoes do job
    steps: 

    - uses: actions/checkout@v3

    - name: Instalando dependências
      run: npm install 

    - name: Testes E2E (end-to-end)  
      run: npm run e2e

    - name: Relatório de cobertura
      uses: actions/upload-artifact@v3 
      with:
        name: Relatorio-cobertura
        path: reports/coverage/lcov.info 


