# CI de Nìvel 01 - Disparo manual a partir de 1 clique

name: 'Execução Manual'

on:
  workflow_dispatch:

jobs:
  e2e-tests:
    runs-on: ['ubuntu-latest']

    steps:
      - uses: actions/checkout@v4

      - name: Instalando Yarn
        run: npm install -g yarn

      - name: Instalando dependências
        working-directory: trabalho-entregue
        run: yarn

      - name: Instalando TypeScript
        working-directory: trabalho-entregue
        run: yarn global add typescript

      - name: Levantar o Servidor em background
        working-directory: ./crud_clientes_node-mai/backend
        run: start &  

      - name: Testes E2E (end-to-end)
        working-directory: trabalho-entregue
        run: yarn run e2e

      - uses: actions/upload-artifact@v4
        if: ${{ !cancelled() }}
        with:
          name: relatorio-de-testes
          path: ./cypress/reports
